version: '3.8'

services:
  # Quick test runner with caching
  quick-test:
    build:
      context: .
      dockerfile: crates/faas-executor/Dockerfile.criu-firecracker-cached
      cache_from:
        - faas-executor-cached:latest
      target: runtime  # Use multi-stage build target if available
    image: faas-executor-cached:latest
    container_name: faas-quick-test
    privileged: true
    network_mode: host
    pid: host
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      # Only mount source directories, not build artifacts
      - ./crates/faas-executor/src:/workspace/crates/faas-executor/src:ro
      - ./crates/faas-executor/tests:/workspace/crates/faas-executor/tests:ro
      - ./faas-lib/src:/workspace/faas-lib/src:ro
      - ./faas-lib/tests:/workspace/faas-lib/tests:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp:exec
      - /run:exec
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info
      - DOCKER_HOST=unix:///var/run/docker.sock
      - CARGO_HOME=/tmp/cargo_home
      - CARGO_TARGET_DIR=/tmp/cargo_target
    command: |
      bash -c "
        echo '=== Quick Test Run ==='

        # Copy source to writable location
        cp -r /workspace /tmp/workspace
        cd /tmp/workspace

        # Run tests with cargo cache
        cargo +nightly test --package faas-executor --lib --release
      "

  # Docker-only tests (fast)
  docker-tests:
    build:
      context: .
      dockerfile: crates/faas-executor/Dockerfile.criu-firecracker-cached
      cache_from:
        - faas-executor-cached:latest
    image: faas-executor-cached:latest
    container_name: faas-docker-tests
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./crates/faas-executor/src:/workspace/crates/faas-executor/src:ro
      - ./crates/faas-executor/tests:/workspace/crates/faas-executor/tests:ro
    environment:
      - RUST_BACKTRACE=1
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: ["/test.sh", "docker"]

  # CRIU tests (requires Linux)
  criu-tests:
    build:
      context: .
      dockerfile: crates/faas-executor/Dockerfile.criu-firecracker-cached
      cache_from:
        - faas-executor-cached:latest
    image: faas-executor-cached:latest
    container_name: faas-criu-tests
    privileged: true
    pid: host
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./crates/faas-executor/src:/workspace/crates/faas-executor/src:ro
      - ./crates/faas-executor/tests:/workspace/crates/faas-executor/tests:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: ["/test.sh", "criu"]

volumes:
  cargo-cache:
    driver: local
  target-cache:
    driver: local