[package]
name = "api-showcase"
version = "0.1.0"
edition = "2021"

[dependencies]
faas-sdk = { path = "../../crates/faas-sdk" }
tokio = { workspace = true }

[[bin]]
name = "showcase"
path = "src/main.rs"