[package]
name = "hash-preimage-guest"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
sp1-zkvm = { version = "5.2", default-features = false, features = ["lib"] }
sha2 = { version = "0.10", default-features = false }
