[env]
# Temporary hack for Tangle blueprints to get the workspace root
#
# See: https://github.com/rust-lang/cargo/issues/3946#issuecomment-973132993
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[target.x86_64-unknown-linux-musl]
linker = "x86_64-linux-musl-gcc"                 # Adjust if your musl-cross compiler has a different name
rustflags = ["-C", "target-feature=+crt-static"]
