[package]
name = "faas-executor"
version = "0.1.0"
edition = "2021"
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"
publish = false

[lib]
name = "faas_executor"
path = "src/lib.rs"

[dependencies]
# Workspace Crates
faas-common = { path = "../faas-common" }

# External Crates
docktopus = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

# Add async-trait
async-trait = "0.1"
thiserror = { workspace = true }
anyhow = { workspace = true }
firecracker-rs-sdk = { version = "0.1.0", features = ["_rt-tokio"] }
serde_json = { workspace = true }
